version: "3"

services:
  app:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    # To link local and docker working directory
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # Expose port -- dependent on Dockerfile
    ports:
      - "80:3000"
    networks:
      - mynetwork
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data_container:
