version: "3"

services:
  app:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    # To link local and docker working directory
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    # Expose port -- dependent on Dockerfile
    ports:
      - "80:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
